# This is a basic workflow to help you get started with Actions

name: Sync Labels across all repos of user

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Get list of all repos of user
        id: get-all-repos-of-user
        run: |
          echo 'USER_REPO_LIST<<EOF' >> $GITHUB_ENV
          gh repo list --source --no-archived --json nameWithOwner | jq -r ".[]|.nameWithOwner" >> $GITHUB_ENV
          echo EOF >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - run: echo "${{ env.USER_REPO_LIST }}"

      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: labels.yml
          repository: ${{ env.USER_REPO_LIST }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
