name: Sync Labels across all repos of user

on:
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  sync-labels:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get list of all repos of user
        id: get-all-repos-of-user
        run: |
          echo 'USER_REPO_LIST<<EOF' >> $GITHUB_ENV
          gh repo list --source --no-archived --json nameWithOwner | jq -r ".[]|.nameWithOwner" >> $GITHUB_ENV
          echo EOF >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: labels.yml
          repository: ${{ env.USER_REPO_LIST }}
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
